stages:
  - build
  - deploy

build dev:
  image: node:18
  stage: build
  only: 
  - dev
  script:
    - yarn install 
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - dist

# unit test:
#   image: node:18
#   stage: test
#   script:
#     - npm install --progress=false
#     - npm run test:unit

deploy dev:
  image: alpine
  stage: deploy
  only: 
  - dev
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ msi@10.11.11.17:/home/msi/dev-cobit-fe.millennia-solusi.xyz/
    - ssh msi@10.11.11.17 "ln -s /home/msi/.htaccess /home/msi/dev-cobit-fe.millennia-solusi.xyz/.htaccess"

build main:
  image: node:18
  stage: build
  only: 
  - main
  script:
    - npm install 
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist

deploy main:
  image: alpine
  stage: deploy
  only: 
  - main
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ msi@10.10.12.8:/home/msi/cobit.millennia-solusi.id/
    - ssh msi@10.10.12.8 "ln -s /home/msi/.htaccess /home/msi/cobit.millennia-solusi.id/.htaccess"
